### ISSUE TITLE
今天api又改了

### ISSUE THREAD

**Issue by wxyttty** [DogeZhang/auto-sign#2]

**Comment by DogeZhang** [comment]
确认整改api，最近一段时间争取修复。

**Comment by wxyttty** [comment]
index- sign.py
82 url = 'https://{host}/wec-counselor-sign-apps/stu/sign/getStuSignInfosInOneDay'.format(host=host)
>> url = 'https://{host}/wec-counselor-sign-apps/stu/sign/queryDailySginTasks'.format(host=host)

110 url='https://{host}/wec-counselor-sign-apps/stu/sign/detailSignInstance'.format(host=host),
>> url='https://{host}/wec-counselor-sign-apps/stu/sign/detailSignTaskInst'.format(host=host),

164 res = session.post(url='https://{host}/wec-counselor-sign-apps/stu/sign/submitSign'.format(host=host),
>> res = session.post(url='https://{host}/wec-counselor-sign-apps/stu/sign/completeSignIn'.format(host=host),

**Comment by DogeZhang** [comment]
已更新，谢谢。
