### ISSUE TITLE
自动签到失败，今日校园版本过低

### ISSUE THREAD

**Issue by wxyttty** [DogeZhang/auto-sign#3]

**Comment by wxyttty** [comment]
'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 (4471302144)cpdaily/8.2.9  wisedu/8.2.9',

def DESEncrypt(s, key='ST83=@XV'):

"model": "iPhone10,1",
    'appVersion': '8.2.9',
    'systemVersion': '13.3.1',
    'systemName': 'iOS',

'RetrofitHeader': '8.2.9',

**Comment by UMRnInside** [comment]
> 'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 (4471302144)cpdaily/8.2.9 wisedu/8.2.9',
> 
> def DESEncrypt(s, key='ST83=@xv'):
> 
> "model": "iPhone10,1",
> 'appVersion': '8.2.9',
> 'systemVersion': '13.3.1',
> 'systemName': 'iOS',
> 
> 'RetrofitHeader': '8.2.9',

能否使用 ``` `` ``` 反引号包裹您的代码？
还有， DES的密钥真的改变了吗?

**Comment by UMRnInside** [comment]
问题部分解决。
DES Key是 `ST83=@XV`
而且似乎不需要增加 `'RetrofitHeader': '8.2.9',`

**Comment by wxyttty** [comment]
原本RetrofitHeader是8.0.8，不知道是否仍可以使用
